### ISSUE TITLE
fyi only (not a real issue)

### ISSUE THREAD

**Issue by jose1711** [hsanjuan/sar2#1]
hello hector,

please note that searchandrescue2 is gone from sf.net and currently your repo is possibly one of the few sources to use for game sources. please do not delete it. thank you, j

**Comment by hsanjuan** [comment]
Hello, I deleted it myself from sourceforge, since I had moved it here and SF has terrible reputation for distributing malware along with package files.

I don't have plans to remove it from here, but you can always fork to be extra sure and keep a copy ;)

**Comment by hsanjuan** [comment]
I have opened #2 to remove references to SF around the code. Thanks for the tip!
